  application: vkpendergrast
  version: 2
  runtime: python27
  api_version: 1
  threadsafe: yes


  inbound_services: 
          - warmup

  handlers:

  - url: /(.+)
    static_files: public/\1
    upload: public/(.*)
    expiration: "0d 30m"

  - url: /
    static_files: public/index.html
    upload: public/index.html
    expiration: "0d 30m"

  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
